import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const master = read('src/pages/master-data.jsx');
const extensions = read('src/pages/inventory-extensions.jsx');
const logistics = read('src/pages/logistics-finance.jsx');
const main = read('src/main.jsx');
const css = read('src/styles/v16-inventory-control.css');
const inventory = master.slice(master.indexOf('export function Inventory('), master.indexOf('function InventoryStockDetail({'));
const movements = logistics.slice(logistics.indexOf('export function InventoryTransactions('), logistics.indexOf('// ============ Accounts Receivable'));

const matches = (name, source, pattern) => test(name, () => assert.match(source, pattern));
const misses = (name, source, pattern) => test(name, () => assert.doesNotMatch(source, pattern));

matches('01 imports isolated P6 stylesheet', main, /v16-inventory-control\.css/);
matches('02 exposes inventory module token', css, /--v16-module-inventory:\s*#168aad/i);
matches('03 caps inventory rail at 680px', css, /width:\s*min\(100%,\s*680px\)/);
matches('04 reserves mobile bottom action space', css, /bottom-nav-height/);
matches('05 inventory uses four-tab navigation', inventory, /aria-label="库存控制"/);
for (const [index, label] of ['库存', '调拨', '盘点', '调整'].entries()) matches(`0${index + 6} tab ${label}`, inventory, new RegExp(`>${label}<`));
matches('10 inventory registers shell back action', inventory, /setHeaderBackAction/);
matches('11 inventory detail and editor are full-page branches', inventory, /screen\.mode === 'editor'/);
misses('12 active P6 inventory surface has no BusinessPageHeader', inventory, /<BusinessPageHeader/);
misses('13 active P6 inventory surface has no HelpDisclosure', inventory, /<HelpDisclosure/);
misses('14 active P6 inventory surface has no Modal', inventory, /<Modal/);
matches('15 stock filters call canonical inventory endpoint', inventory, /api\('\/api\/inventory\?'/);
matches('16 stock detail uses canonical detail endpoint', inventory, /api\(`\/api\/inventory\/\$\{value\.warehouse_id\}\/\$\{value\.product_id\}`\)/);
matches('17 stock detail labels event timestamp as record time', inventory, /记录时间 \{dateTime\(tx\.createdAt\)\}/);
matches('18 missing business dates are explicit', inventory, /业务日期缺失/);
matches('19 transfer has exact current filters', inventory, /\['TRANSFERRED','已调拨'\]/);
matches('20 transfer legacy submitted is read-only label', inventory, /SUBMITTED' \? '历史待审核'/);
matches('21 transfer legacy approved is read-only label', inventory, /APPROVED' \? '历史已审核'/);
matches('22 transfer canonical confirm permission is primary', inventory, /INVENTORY_TRANSFER_CONFIRM/);
matches('23 transfer approve permission is compatibility alias', inventory, /INVENTORY_TRANSFER_APPROVE/);
matches('24 transfer confirm calls execution endpoint', inventory, /inventory-transfers\/\$\{value\.id\}\/\$\{action\}/);
matches('25 transfer action says confirm transfer', inventory, />确认调拨</);
matches('26 transfer tracking is source-warehouse OUT', inventory, /warehouseId=\{form\.fromWarehouseId\}[\s\S]*?direction="OUT"/);
matches('27 stocktake filters approval states', inventory, /\['SUBMITTED','审批中'\]/);
matches('28 stocktake submits exact SUBMIT action', inventory, /body:\s*\{ action: 'SUBMIT' \}/);
matches('29 submitted stocktake navigates to approvals', inventory, /page="approvals">前往审批中心/);
matches('30 stocktake tracking uses absolute difference', inventory, /quantity=\{Math\.abs\(difference\)\}/);
matches('31 stocktake tracking direction follows difference', inventory, /direction=\{difference >= 0 \? 'IN' : 'OUT'\}/);
matches('32 adjustment keeps signed quantityDelta', inventory, /有符号调整数量/);
matches('33 adjustment tracking uses absolute delta', inventory, /Math\.abs\(Number\(row\.quantityDelta\)/);
matches('34 adjustment preserves ConfirmDelete contract', inventory, /<ConfirmDelete label="库存调整单"/);
matches('35 scrap list/detail/editor are full-page states', extensions, /screen\?\.mode === 'editor'[\s\S]*screen\?\.mode === 'detail'/);
matches('36 scrap tracking is OUT', extensions, /businessDate=\{form\.scrapDate\} direction="OUT"/);
matches('37 scrap warns all-or-nothing confirmation', extensions, /任一行库存不足时整单不会生效/);
misses('38 scrap has no archive experience', extensions, /lifecycle|归档|恢复/);
matches('39 month-end invokes mandatory precheck', extensions, /inventory-period-closures\/check/);
matches('40 period change invalidates precheck', extensions, /setPrecheck\(null\); setPrecheckedPeriod\(''\)/);
matches('41 blocked precheck disables close', extensions, /overallStatus !== 'BLOCKED'/);
matches('42 warning requires explicit checkbox', extensions, /warning \|\| confirmWarnings/);
matches('43 warning confirmation reaches API', extensions, /confirmWarnings:\s*warning && confirmWarnings/);
matches('44 reopen requires a reason', extensions, /if \(!reason\.trim\(\)\) return/);
matches('45 month-end summary is authoritative 2x2', extensions, /warehouseCount[\s\S]*productCount[\s\S]*totalInQuantity[\s\S]*totalOutQuantity/);
misses('46 month-end does not sum heterogeneous closing quantities', extensions, /totalClosing|closingQuantity\)\s*\+/);
matches('47 movement filters label created-at range as record date', movements, /记录日期从[\s\S]*记录日期至/);
matches('48 movement row uses business_date only', movements, /item\.business_date \|\| '业务日期缺失'/);
matches('49 NONE tracking renders dash', movements, /trackingPolicy === 'NONE' \? '—'/);
matches('50 missing historical identity is explicit', movements, /历史记录未采集/);
misses('51 movement P6 surface has no BusinessPageHeader', movements, /<BusinessPageHeader/);
misses('52 movement P6 surface has no table', movements, /<table/);
matches('53 responsive breakpoints include 390 and 340', css, /max-width:\s*390px[\s\S]*max-width:\s*340px/);
matches('54 P6 rows are true buttons', inventory, /function InventoryRowV16[\s\S]*<button type="button"/);
