import { useEffect, useMemo, useState } from 'react';
import { api } from '../api.js';
import { Empty, Loading, Modal, Panel, Status, money, quantity } from '../components/ui.jsx';

function Totals({ net = 0, tax = 0, gross = 0 }) {
  return <dl className="commercial-totals"><div><dt>净额</dt><dd>{money(net)}</dd></div><div><dt>税额</dt><dd>{money(tax)}</dd></div><div><dt>含税总额</dt><dd>{money(gross)}</dd></div></dl>;
}

function CommercialList({ kind, notify }) {
  const sales = kind === 'sales'; const endpoint = sales ? '/api/sales-invoices' : '/api/supplier-bills';
  const [rows, setRows] = useState(null); const [open, setOpen] = useState(false);
  const load = () => api(endpoint).then(r => setRows(sales ? r.salesInvoices : r.supplierBills)).catch(e => notify(e.message, 'error'));
  useEffect(() => { void load(); }, []);
  return <Panel title={sales ? '销售发票' : '供应商账单'} subtitle={sales ? '交付与计费分离；发票是 AR、收入与销项税的权威来源' : '收货先记 GRNI；账单匹配后生成 AP、进项税与价差'} action={<button className="primary" onClick={() => setOpen(true)}>＋ {sales ? '从出货开票' : '从收货建账单'}</button>}>
    {rows === null ? <Loading/> : <div className="table-wrap"><table><thead><tr><th>单号</th><th>{sales ? '客户' : '供应商'}</th><th>日期</th><th>税模式</th><th className="number">净额</th><th className="number">税额</th><th className="number">含税</th><th>状态</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="mono">{sales?row.invoice_no:row.bill_no}</td><td>{sales?row.customerName:row.supplierName}</td><td>{sales?row.invoice_date:row.bill_date}</td><td>{row.tax_mode}</td><td className="number">{money(row.net_cents)}</td><td className="number">{money(row.tax_cents)}</td><td className="number"><strong>{money(row.gross_cents)}</strong></td><td><Status status={row.status.toLowerCase()} label={row.status}/></td></tr>)}</tbody></table>{!rows.length&&<Empty text={sales?'暂无销售发票':'暂无供应商账单'}/>}</div>}
    {open&&<SourceBillingModal sales={sales} onClose={()=>{setOpen(false);void load();}} notify={notify}/>}</Panel>;
}

function SourceBillingModal({ sales, onClose, notify }) {
  const [sources,setSources]=useState([]),[detail,setDetail]=useState(null),[taxCodes,setTaxCodes]=useState([]); const today=new Date().toISOString().slice(0,10);
  const [form,setForm]=useState({sourceId:'',date:today,taxMode:'NO_TAX',taxCode:'',supplierInvoiceNo:'',items:[]});
  useEffect(()=>{api(sales?'/api/sales-deliveries?status=CONFIRMED':'/api/purchase-receipts?status=CONFIRMED').then(r=>setSources(sales?r.salesDeliveries:r.purchaseReceipts)).catch(e=>notify(e.message,'error'));api('/api/tax-codes').then(r=>setTaxCodes(r.taxCodes||[])).catch(()=>{});},[]);
  const choose=async sourceId=>{setForm(f=>({...f,sourceId}));if(!sourceId)return setDetail(null);const r=await api(`${sales?'/api/sales-deliveries/':'/api/purchase-receipts/'}${sourceId}`);const d=sales?r.salesDelivery:r.purchaseReceipt;setDetail(d);setForm(f=>({...f,sourceId,items:d.items.filter(x=>x.remainingBillQuantity>0).map(x=>({sourceItemId:x.id,quantity:x.remainingBillQuantity,unitPriceCents:x.unitPriceCents,taxCode:f.taxCode}))}));};
  const projected=useMemo(()=>form.items.reduce((s,x)=>s+x.quantity*x.unitPriceCents,0),[form.items]);
  const save=async()=>{try{const common={taxMode:form.taxMode,[sales?'invoiceDate':'billDate']:form.date,[sales?'customerId':'supplierId']:sales?detail.customer_id:detail.supplier_id,items:form.items.map(x=>({[sales?'deliveryItemId':'receiptItemId']:x.sourceItemId,quantity:x.quantity,unitPriceCents:x.unitPriceCents,taxCode:form.taxMode==='NO_TAX'?null:form.taxCode}))};if(!sales)common.supplierInvoiceNo=form.supplierInvoiceNo;const created=await api(sales?'/api/sales-invoices':'/api/supplier-bills',{method:'POST',body:common});await api(`${sales?'/api/sales-invoices/':'/api/supplier-bills/'}${created.id}/post`,{method:'POST',body:{}});notify(sales?'销售发票已过账':'供应商账单已过账');onClose();}catch(e){notify(e.message,'error');}};
  return <Modal title={sales?'从已确认出货开票':'从已确认收货建账单'} onClose={onClose} wide><form className="form-grid" onSubmit={e=>{e.preventDefault();void save();}}><label className="full">权威来源<select value={form.sourceId} onChange={e=>void choose(e.target.value)} required><option value="">选择已确认单据</option>{sources.filter(x=>x.remainingBillQuantity>0).map(x=><option key={x.id} value={x.id}>{sales?x.delivery_no:x.receipt_no} · 剩余 {quantity(x.remainingBillQuantity)}</option>)}</select><small>客户/供应商、产品、已交付数量和原始价格由来源单据带入。</small></label><label>单据日期<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label>{!sales&&<label>供应商发票号<input value={form.supplierInvoiceNo} onChange={e=>setForm({...form,supplierInvoiceNo:e.target.value})} required/></label>}<label>税模式<select value={form.taxMode} onChange={e=>setForm({...form,taxMode:e.target.value})}><option value="NO_TAX">不含税业务</option><option value="EXCLUSIVE">价外税</option><option value="INCLUSIVE">价内税</option></select></label>{form.taxMode!=='NO_TAX'&&<label>税码<select value={form.taxCode} onChange={e=>setForm({...form,taxCode:e.target.value})} required><option value="">选择税码</option>{taxCodes.filter(x=>x.active).map(x=><option key={x.id} value={x.code}>{x.code} · {x.name}</option>)}</select></label>}<div className="full source-facts">{detail?<><div><span>往来单位</span><strong>{sales?detail.customerName:detail.supplierName}</strong></div><div><span>计费模式</span><strong>{detail.billing_mode}</strong></div><div><span>本次未税基数</span><strong>{money(projected)}</strong></div></>:<p>选择来源后显示不可篡改的业务事实。</p>}</div>{detail&&<div className="full table-wrap"><table className="line-table"><thead><tr><th>产品</th><th>单位换算</th><th className="number">本次数量</th><th className="number">单价</th></tr></thead><tbody>{form.items.map(x=>{const source=detail.items.find(i=>i.id===x.sourceItemId);return <tr key={x.sourceItemId}><td>{source.productCode} · {source.productName}</td><td>{source.document_uom_code||source.unit} → 基础单位</td><td><input type="number" min="0.0001" max={source.remainingBillQuantity} step="any" value={x.quantity} onChange={e=>setForm({...form,items:form.items.map(i=>i.sourceItemId===x.sourceItemId?{...i,quantity:Number(e.target.value)}:i)})}/></td><td className="number">{money(x.unitPriceCents)}</td></tr>})}</tbody></table></div>}<div className="full"><Totals net={projected} gross={projected}/></div><div className="form-actions full"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary" disabled={!detail}>创建并过账</button></div></form></Modal>;
}

export const SalesInvoices=({notify})=><CommercialList kind="sales" notify={notify}/>;
export const SupplierBills=({notify})=><CommercialList kind="purchase" notify={notify}/>;

const STEPS=['Upload','Validate','Preview','Reconcile','Submit','Review','Activate'];
export function GoLive({ notify }) {
  const [state,setState]=useState({batches:[],goLive:null});const [entityType,setEntityType]=useState('customers'),[csv,setCsv]=useState('code,name\nC001,客户名称'),[importBatch,setImportBatch]=useState(null),[preview,setPreview]=useState([]);
  const load=()=>api('/api/opening-batches').then(r=>setState({batches:r.openingBatches||[],goLive:r.goLive})).catch(e=>notify(e.message,'error'));useEffect(()=>{void load();},[]);
  const stage=async()=>{try{const b=await api('/api/imports',{method:'POST',body:{entityType,csv,idempotencyKey:`ui-${entityType}-${Date.now()}`}});setImportBatch(b);notify('文件已进入隔离区，未写入业务表');}catch(e){notify(e.message,'error');}};
  const validate=async()=>{try{const r=await api(`/api/imports/${importBatch.id}/validate`,{method:'POST',body:{}});setPreview(r.rows||[]);notify(r.valid?'逐行校验通过':'存在需要修正的行','error');}catch(e){notify(e.message,'error');}};
  const commit=async()=>{try{await api(`/api/imports/${importBatch.id}/commit`,{method:'POST',body:{}});notify('导入批次已原子提交');}catch(e){notify(e.message,'error');}};
  return <Panel title="Go-Live 受控上线" subtitle="期初数据在隔离区校验、核对和独立复核后才能启用"><ol className="go-live-rail">{STEPS.map((s,i)=><li key={s} className={i<3&&importBatch?'active':''}><span>{String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol><section className="go-live-workbench"><div><h3>导入隔离区</h3><label>数据集<select value={entityType} onChange={e=>setEntityType(e.target.value)}><option value="customers">客户</option><option value="suppliers">供应商</option><option value="products">产品</option><option value="uoms">UOM / 换算</option><option value="warehouses">仓库</option><option value="opening_balance">期初余额</option></select></label><label>CSV<textarea rows="8" value={csv} onChange={e=>setCsv(e.target.value)}/></label><div className="form-actions"><button className="secondary" onClick={()=>void stage()}>Upload / Stage</button><button className="secondary" disabled={!importBatch} onClick={()=>void validate()}>Validate / Preview</button><button className="primary" disabled={!preview.length||preview.some(x=>JSON.parse(x.errors_json||'[]').length)} onClick={()=>void commit()}>Commit</button></div></div><aside><span className="eyebrow">上线锁</span><strong>{state.goLive?.status||'PREPARING'}</strong><p>{state.goLive?.status==='ACTIVE'?'期初批次已永久锁定。':'系统尚允许编制期初批次。'}</p><h4>最近期初批次</h4>{state.batches.map(x=><div className="opening-row" key={x.id}><span className="mono">{x.batch_no}</span><Status status={x.status.toLowerCase()} label={x.status}/></div>)}{!state.batches.length&&<p className="muted">尚无期初批次。</p>}</aside></section></Panel>;
}
