import { useEffect, useState } from 'react';
import { api } from '../api.js';
import { Loading, can, dateTime, quantity } from '../components/ui.jsx';
import { BottomActionBar, ConfirmSheet, DangerSheet, EmptyState, InlineAlert, SearchField, SegmentedControl, StatusChip } from '../components/design-system.jsx';
import { AppLink, useAppNavigation } from '../navigation/AppNavigationContext.jsx';
import TrackingAllocationEditor from '../components/TrackingAllocationEditor.jsx';
import { withProductTracking } from '../lib/tracking.js';

const today = () => new Date().toISOString().slice(0, 10);
const businessDate = (value) => value || '业务日期缺失';
const STATUS = { DRAFT: '草稿', CONFIRMED: '已确认', CANCELLED: '已取消', CLOSED: '已结账', REOPENED: '已反结账' };
function Shell({ className = '', children }) { return <main className={`business-page-shell business-page-shell--rail v16-inventory-shell ${className}`.trim()}>{children}</main>; }
function Row({ code, title, status, lines, metric, onClick }) { return <button type="button" className="v16-inventory-row" onClick={onClick}><span className="v16-inventory-row__body"><span className="v16-inventory-row__top"><b className="mono">{code}</b>{status}</span><strong>{title}</strong>{lines.map((line, index) => <small key={index}>{line}</small>)}{metric && <b className="v16-inventory-row__metric">{metric}</b>}</span></button>; }
function Identity({ code, title, status, subtitle }) { return <header className="v16-inventory-identity"><div><span className="mono">{code}</span><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{status}</header>; }
function Facts({ facts }) { return <dl className="v16-inventory-facts">{facts.map((fact) => <div key={fact.label}><dt>{fact.label}</dt><dd>{fact.value ?? '—'}</dd></div>)}</dl>; }
function Lines({ items = [] }) { return <section className="v16-inventory-section"><h3>明细</h3><div className="v16-inventory-list">{items.map((item, index) => <div className="v16-inventory-line" key={item.id || index}><div><b>{item.productName}</b><small className="mono">{item.productCode}</small><small>{item.warehouseName || item.reason || ''}</small></div><strong>{quantity(item.quantity)} {item.productUnit || item.unit || ''}</strong></div>)}</div></section>; }
function useBack(active, back) { const navigation = useAppNavigation(); useEffect(() => { navigation.setHeaderBackAction?.(active ? back : null); return () => navigation.setHeaderBackAction?.(null); }, [active, back, navigation.setHeaderBackAction]); }

export function InventoryScraps({ user, notify }) {
  const [rows, setRows] = useState([]); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [screen, setScreen] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [warehouses, setWarehouses] = useState([]); const [products, setProducts] = useState([]);
  const load = () => { setLoading(true); setError(''); api(`/api/inventory-scraps${status ? `?status=${status}` : ''}`).then((r) => setRows(r.inventoryScraps || [])).catch((e) => { setError(e.message); notify(e.message, 'error'); }).finally(() => setLoading(false)); };
  useEffect(() => { void load(); }, [status]);
  useEffect(() => { Promise.all([api('/api/warehouses'), api('/api/products')]).then(([w, p]) => { setWarehouses((w.warehouses || []).filter((x) => x.active)); setProducts((p.products || []).filter((x) => x.active)); }).catch((e) => notify(e.message, 'error')); }, []);
  useBack(Boolean(screen), () => setScreen(null));
  const open = async (row) => { try { const result = await api(`/api/inventory-scraps/${row.id}`); setScreen({ mode: 'detail', value: result.inventoryScrap }); } catch (e) { notify(e.message, 'error'); } };
  if (screen?.mode === 'editor') return <InventoryScrapEditor value={screen.value || {}} warehouses={warehouses} products={products} notify={notify} onSaved={() => { setScreen(null); void load(); }}/>;
  if (screen?.mode === 'detail') return <InventoryScrapDetail value={screen.value} user={user} notify={notify} onEdit={() => setScreen({ mode: 'editor', value: screen.value })} onChanged={() => { setScreen(null); void load(); }}/>;
  const visible = rows.filter((row) => `${row.scrapNo} ${row.reason}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <Shell className="v16-inventory-scraps"><div className="v16-inventory-tools"><SearchField value={search} onChange={setSearch} placeholder="搜索报废单号或原因"/>{can(user, 'INVENTORY_SCRAP_MANAGE') && <button className="primary" onClick={() => setScreen({ mode: 'editor', value: {} })}>新建</button>}</div><SegmentedControl value={status} onChange={setStatus} options={[['','全部'],['DRAFT','草稿'],['CONFIRMED','已确认'],['CANCELLED','已取消']].map(([value,label]) => ({ value, label }))}/>{loading ? <Loading/> : error ? <EmptyState title="加载失败" description={error} action={<button className="secondary" onClick={load}>重试</button>}/> : visible.length ? <div className="v16-inventory-list">{visible.map((row) => <Row key={row.id} code={row.scrapNo} title={row.reason || '未填写原因'} status={<StatusChip status={row.status}>{STATUS[row.status]}</StatusChip>} lines={[businessDate(row.scrapDate), `${row.itemCount} 项 · ${row.creatorName}`]} metric={quantity(row.totalQuantity)} onClick={() => void open(row)}/>)}</div> : <EmptyState title={search || status ? '没有匹配结果' : '暂无报废记录'}/>}</Shell>;
}

function InventoryScrapEditor({ value, warehouses, products, notify, onSaved }) {
  const initial = value.items?.map((item) => ({ warehouseId: item.warehouseId, productId: item.productId, quantity: item.quantity, reason: item.reason || '', trackingAllocations: item.trackingAllocations || [] })) || [{ warehouseId: '', productId: '', quantity: '', reason: '', trackingAllocations: [] }];
  const [form, setForm] = useState({ scrapDate: value.scrap_date || today(), reason: value.reason || '', notes: value.notes || '', items: initial }); const update = (i, patch) => setForm({ ...form, items: form.items.map((row, index) => index === i ? { ...row, ...patch } : row) });
  const save = async (event) => { event.preventDefault(); try { await api(value.id ? `/api/inventory-scraps/${value.id}` : '/api/inventory-scraps', { method: value.id ? 'PATCH' : 'POST', body: form }); notify('报废草稿已保存'); onSaved(); } catch (e) { notify(e.message, 'error'); } };
  return <Shell className="v16-inventory-editor"><form onSubmit={save}><h2>{value.id ? '编辑存货报废' : '新建存货报废'}</h2><div className="v16-inventory-form-grid"><label>报废日期<input type="date" required value={form.scrapDate} onChange={(e) => setForm({ ...form, scrapDate: e.target.value })}/></label><label>报废原因<input value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })}/></label><label>备注<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label></div><section className="v16-inventory-section"><header><h3>报废明细</h3><button type="button" className="secondary" onClick={() => setForm({ ...form, items: [...form.items, { warehouseId: '', productId: '', quantity: '', reason: '', trackingAllocations: [] }] })}>添加一行</button></header><div className="v16-inventory-lines">{form.items.map((line, index) => <article key={index}><div className="v16-inventory-line-head"><b>第 {index + 1} 行</b><button type="button" className="ghost" disabled={form.items.length === 1} onClick={() => setForm({ ...form, items: form.items.filter((_, i) => i !== index) })}>移除</button></div><select aria-label="仓库" required value={line.warehouseId} onChange={(e) => update(index, { warehouseId: e.target.value })}><option value="">选择仓库</option>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select><select aria-label="货品" required value={line.productId} onChange={(e) => update(index, withProductTracking(line, e.target.value))}><option value="">选择货品</option>{products.map((p) => <option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><input aria-label="报废数量" type="number" min="0.01" step="0.01" required value={line.quantity} onChange={(e) => update(index, { quantity: e.target.value, trackingAllocations: [] })}/><input aria-label="行原因" value={line.reason} onChange={(e) => update(index, { reason: e.target.value })}/><TrackingAllocationEditor product={products.find((p) => p.id === line.productId)} warehouseId={line.warehouseId} quantity={line.quantity} businessDate={form.scrapDate} direction="OUT" value={line.trackingAllocations || []} onChange={(trackingAllocations) => update(index, { trackingAllocations })} notify={notify}/></article>)}</div></section><BottomActionBar><button className="primary">保存草稿</button></BottomActionBar></form></Shell>;
}
function InventoryScrapDetail({ value, user, notify, onEdit, onChanged }) {
  const [action, setAction] = useState(null); const change = async (name) => { try { await api(`/api/inventory-scraps/${value.id}/${name}`, { method: 'POST' }); notify(name === 'confirm' ? '报废单已确认' : '报废单已取消'); onChanged(); } catch (e) { notify(e.message, 'error'); } };
  return <Shell className="v16-inventory-detail"><Identity code={value.scrap_no} title={value.reason || '存货报废'} status={<StatusChip status={value.status}>{STATUS[value.status]}</StatusChip>} subtitle={value.notes}/><Facts facts={[{ label: '报废日期', value: businessDate(value.scrap_date) }, { label: '创建人', value: value.creatorName }, { label: '确认人', value: value.confirmedByName || '—' }, { label: '确认时间', value: dateTime(value.confirmed_at) }]}/><Lines items={value.items}/>{value.status === 'CONFIRMED' && <div className="v16-inventory-inline-link"><AppLink page="inventory-transactions">查看库存异动</AppLink></div>}{value.status === 'DRAFT' && can(user, 'INVENTORY_SCRAP_MANAGE') && <BottomActionBar><button className="secondary" onClick={onEdit}>编辑草稿</button><button className="danger-button" onClick={() => setAction('cancel')}>取消报废</button><button className="primary" onClick={() => setAction('confirm')}>确认报废</button></BottomActionBar>}{action === 'confirm' && <ConfirmSheet title="确认整单报废？" message="系统会先校验全部明细；任一行库存不足时整单不会生效。" confirmLabel="确认报废" onClose={() => setAction(null)} onConfirm={() => void change('confirm')}/>} {action === 'cancel' && <DangerSheet title="取消报废？" message="取消后不会扣减库存。" confirmLabel="取消报废" onClose={() => setAction(null)} onConfirm={() => void change('cancel')}/>}</Shell>;
}

export function InventoryMonthEnd({ user, notify }) {
  const [rows, setRows] = useState([]); const [periodStatus, setPeriodStatus] = useState(null); const [screen, setScreen] = useState(null); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); Promise.all([api('/api/inventory-period-closures'), api('/api/inventory-period-closures/status')]).then(([list, state]) => { setRows(list.inventoryPeriodClosures || []); setPeriodStatus(state.status); }).catch((e) => notify(e.message, 'error')).finally(() => setLoading(false)); };
  useEffect(() => { void load(); }, []); useBack(Boolean(screen), () => setScreen(null));
  const open = async (row) => { try { const result = await api(`/api/inventory-period-closures/${row.id}`); setScreen({ mode: 'detail', value: result.inventoryPeriodClosure }); } catch (e) { notify(e.message, 'error'); } };
  if (screen?.mode === 'close') return <InventoryCloseTask initialPeriod={periodStatus?.nextClosablePeriod} notify={notify} onSaved={() => { setScreen(null); void load(); }}/>;
  if (screen?.mode === 'detail') return <InventoryPeriodDetail value={screen.value} user={user} periodStatus={periodStatus} notify={notify} onChanged={() => { setScreen(null); void load(); }}/>;
  return <Shell className="v16-inventory-month-end"><div className="v16-inventory-month-head"><div><small>已结至</small><strong>{periodStatus?.closedThrough || '尚无结账基线'}</strong></div>{can(user, 'INVENTORY_PERIOD_CLOSE_MANAGE') && <button className="primary" disabled={!periodStatus?.canClose} onClick={() => setScreen({ mode: 'close' })}>执行月结</button>}</div>{loading ? <Loading/> : rows.length ? <div className="v16-inventory-list">{rows.map((row) => <Row key={row.id} code={row.period_key} title={row.status === 'REOPENED' ? '等待重新结账' : '存货期间已关闭'} status={<StatusChip status={row.status}>{STATUS[row.status]}</StatusChip>} lines={[`${row.snapshotCount} 条快照`, `结账人 ${row.closedByName} · ${dateTime(row.closed_at)}`]} onClick={() => void open(row)}/>)}</div> : <EmptyState title="尚未执行存货月结"/>}</Shell>;
}
function InventoryCloseTask({ initialPeriod, notify, onSaved }) {
  const [period, setPeriod] = useState(initialPeriod || today().slice(0, 7)); const [notes, setNotes] = useState(''); const [precheck, setPrecheck] = useState(null); const [precheckedPeriod, setPrecheckedPeriod] = useState(''); const [confirmWarnings, setConfirmWarnings] = useState(false); const [checking, setChecking] = useState(false);
  const check = async () => { setChecking(true); try { const result = await api('/api/inventory-period-closures/check', { method: 'POST', body: { period } }); setPrecheck(result.precheck); setPrecheckedPeriod(period); setConfirmWarnings(false); } catch (e) { notify(e.message, 'error'); } finally { setChecking(false); } };
  const current = precheckedPeriod === period ? precheck : null; const warning = current?.overallStatus === 'WARNING'; const ready = current && current.overallStatus !== 'BLOCKED' && (!warning || confirmWarnings);
  const close = async (event) => { event.preventDefault(); if (!ready) return; try { await api('/api/inventory-period-closures', { method: 'POST', body: { period, notes, confirmWarnings: warning && confirmWarnings } }); notify(`期间 ${period} 已结账`); onSaved(); } catch (e) { notify(e.message, 'error'); } };
  return <Shell className="v16-inventory-editor"><form onSubmit={close}><h2>执行存货月结</h2><div className="v16-inventory-form-grid"><label>结账期间<input aria-label="结账期间" value={period} pattern="\d{4}-(0[1-9]|1[0-2])" onChange={(e) => { setPeriod(e.target.value); setPrecheck(null); setPrecheckedPeriod(''); setConfirmWarnings(false); }} required/></label><label>结账备注<textarea value={notes} onChange={(e) => setNotes(e.target.value)}/></label></div>{current ? <PrecheckResults value={current}/> : <EmptyState title="尚未运行预检查" description="选择期间后先运行预检查。"/>}{warning && <label className="v16-inventory-warning-confirm"><input type="checkbox" checked={confirmWarnings} onChange={(e) => setConfirmWarnings(e.target.checked)}/>我已审阅并接受上述非阻断警告</label>}<BottomActionBar><button type="button" className="secondary" disabled={checking} onClick={() => void check()}>{checking ? '检查中…' : '运行预检查'}</button><button className="primary" disabled={!ready}>确认结账</button></BottomActionBar></form></Shell>;
}
function PrecheckResults({ value }) { const tone = value.overallStatus === 'PASS' ? 'success' : value.overallStatus === 'WARNING' ? 'warning' : 'danger'; const label = { PASS: '可以结账', WARNING: '存在警告', BLOCKED: '暂不能结账' }[value.overallStatus]; return <section className="v16-inventory-precheck"><InlineAlert tone={tone} title={label}>阻断 {value.summary.blockingCount} · 警告 {value.summary.warningCount} · 通过 {value.summary.passCount}</InlineAlert>{value.checks.map((check) => <article key={check.code} className={`is-${check.status.toLowerCase()}`}><div><b>{check.title}</b><span>{check.status === 'PASS' ? '通过' : check.severity === 'WARNING' ? '警告' : '阻断'}{check.count ? ` · ${check.count}` : ''}</span></div>{check.status === 'FAIL' && check.resolution && <p>{check.resolution}</p>}</article>)}</section>; }
function InventoryPeriodDetail({ value, user, periodStatus, notify, onChanged }) {
  const [reopen, setReopen] = useState(false); const [reason, setReason] = useState(''); const canReopen = can(user, 'INVENTORY_PERIOD_CLOSE_MANAGE') && value.status === 'CLOSED' && periodStatus?.latestPeriod === value.period_key;
  const submitReopen = async () => { if (!reason.trim()) return; try { await api(`/api/inventory-period-closures/${value.id}/reopen`, { method: 'POST', body: { reason } }); notify(`期间 ${value.period_key} 已反结账`); onChanged(); } catch (e) { notify(e.message, 'error'); } };
  return <Shell className="v16-inventory-detail"><Identity code={value.period_key} title="存货月结快照" status={<StatusChip status={value.status}>{STATUS[value.status]}</StatusChip>} subtitle={`${value.periodRange?.startDate} 至 ${value.periodRange?.endDate}`}/><Facts facts={[{ label: '仓库数', value: value.summary?.warehouseCount || 0 }, { label: '货品数', value: value.summary?.productCount || 0 }, { label: '期内入库', value: quantity(value.summary?.totalInQuantity || 0) }, { label: '期内出库', value: quantity(value.summary?.totalOutQuantity || 0) }]}/>{value.closeChecks && <PrecheckResults value={value.closeChecks}/>}<section className="v16-inventory-section"><h3>期末快照</h3>{value.snapshots?.length ? <div className="v16-inventory-list">{value.snapshots.map((snap) => <div className="v16-inventory-snapshot" key={snap.id}><div><b>{snap.productName}</b><small className="mono">{snap.productCode}</small><small>{snap.warehouseName}</small></div><dl><div><dt>入</dt><dd>{quantity(snap.periodInQuantity)}</dd></div><div><dt>出</dt><dd>{quantity(snap.periodOutQuantity)}</dd></div><div><dt>期末</dt><dd>{quantity(snap.closingQuantity)}</dd></div></dl></div>)}</div> : <EmptyState title="该期间无快照"/>}</section><div className="v16-inventory-inline-link"><AppLink page="inventory-transactions">按记录日期查看库存异动</AppLink></div>{canReopen && <BottomActionBar><button className="danger-button" onClick={() => setReopen(true)}>反结账</button></BottomActionBar>}{reopen && <DangerSheet title={`反结账 ${value.period_key}？`} confirmLabel="确认反结账" onClose={() => setReopen(false)} onConfirm={() => void submitReopen()}><label>反结账原因<textarea value={reason} onChange={(e) => setReason(e.target.value)} required/></label></DangerSheet>}</Shell>;
}
export default function InventoryExtensions({ user, notify, page }) { return page === 'inventory-month-end' ? <InventoryMonthEnd user={user} notify={notify}/> : <InventoryScraps user={user} notify={notify}/>; }
