import { useEffect, useMemo, useState } from 'react';
import { api } from '../api.js';
import { AppLink, useAppNavigation } from '../navigation/AppNavigationContext.jsx';
import { Empty, FormActions, Loading, Modal, Panel, Status, Toolbar, YuanField, can, money } from '../components/ui.jsx';

const sourceLabels = { SALES_DELIVERY: '销售出货', SALES_RETURN: '销售退货', PURCHASE_RECEIPT: '采购入库', PURCHASE_RETURN: '采购退货' };
const sourcePages = { SALES_DELIVERY: 'sales-deliveries', SALES_RETURN: 'returns', PURCHASE_RECEIPT: 'purchase-receipts', PURCHASE_RETURN: 'returns' };

export function Receivables(props) { return <AccountList {...props} kind="AR"/>; }
export function Payables(props) { return <AccountList {...props} kind="AP"/>; }

function AccountList({ kind, notify }) {
  const { target } = useAppNavigation();
  const ar = kind === 'AR'; const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [partyId, setPartyId] = useState(''); const [parties, setParties] = useState([]); const [detail, setDetail] = useState(null); const [loading, setLoading] = useState(true); const [statement, setStatement] = useState(null);
  const base = ar ? '/api/accounts-receivable' : '/api/accounts-payable'; const partyKey = ar ? 'customer' : 'supplier';
  const load = async () => { setLoading(true); try { const q = new URLSearchParams({ search, ...(status && { status }), ...(partyId && { [partyKey]: partyId }) }); const data = await api(`${base}?${q}`); setItems(data[ar ? 'receivables' : 'payables'] || []); } catch (error) { notify(error.message, 'error'); } finally { setLoading(false); } };
  useEffect(() => { api(`/api/settlement/${ar ? 'customers' : 'suppliers'}`).then((data) => setParties(data[ar ? 'customers' : 'suppliers'] || [])).catch((error) => notify(error.message, 'error')); }, []);
  useEffect(() => { void load(); }, [status, partyId]);
  const openDetail = async (item) => { try { const data = await api(`${base}/${item.id}`); setDetail(data[ar ? 'receivable' : 'payable']); } catch (error) { notify(error.message, 'error'); } };
  useEffect(() => { if (target?.page === (ar ? 'accounts-receivable' : 'accounts-payable') && target.documentId) void openDetail({ id: target.documentId }); }, [target?.page, target?.documentId]);
  const loadStatement = async () => { if (!partyId) return notify(`请先选择${ar ? '客户' : '供应商'}`, 'error'); try { setStatement(await api(`${base}/statement?${partyKey}=${encodeURIComponent(partyId)}&dateFrom=0000-01-01&dateTo=9999-12-31`)); } catch (error) { notify(error.message, 'error'); } };
  return <Panel title={ar ? '应收账款' : '应付账款'}>
    <Toolbar search={search} setSearch={setSearch} onSearch={load} placeholder={`搜索业务单号或${ar ? '客户' : '供应商'}`} extra={<div className="settlement-filters"><select aria-label={ar ? '客户筛选' : '供应商筛选'} value={partyId} onChange={(e) => setPartyId(e.target.value)}><option value="">全部{ar ? '客户' : '供应商'}</option>{parties.map((p) => <option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><select aria-label="状态筛选" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">全部状态</option><option value="OPEN">未结清</option><option value="PARTIALLY_SETTLED">{ar ? '部分收款' : '部分付款'}</option><option value="SETTLED">已结清</option></select><button className="secondary" onClick={loadStatement}>{ar ? '客户对账单' : '供应商对账单'}</button></div>}/>
    {loading ? <Loading/> : <div className="table-wrap settlement-table"><table><thead><tr><th>{ar ? '客户' : '供应商'}</th><th>业务单号 / 来源</th><th>业务日期</th><th className="number">原始金额</th><th className="number">冲减</th><th className="number">{ar ? '已收' : '已付'}</th><th className="number">{ar ? '未收' : '未付'}</th><th>状态</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="clickable" onClick={() => openDetail(item)}><td className="settlement-party"><strong>{item[ar ? 'customerName' : 'supplierName']}</strong></td><td><span className="mono strong-text">{item.source_no}</span><small className="block">{sourceLabels[item.source_type]}</small></td><td>{item.business_date}</td><td className="number">{money(item.originalCents)}</td><td className="number credit-amount">{money(item.adjustmentCents)}</td><td className="number">{money(item.settledCents)}</td><td className="number settlement-outstanding"><small>{ar ? '未收' : '未付'}</small><strong>{money(item.outstandingCents)}</strong></td><td><Status status={item.status} label={item.statusLabel}/></td></tr>)}</tbody></table>{!items.length && <Empty title={`暂无${ar ? '应收' : '应付'}记录`} text="当前筛选条件下没有记录。"/>}</div>}
    {detail && <AccountDetail item={detail} ar={ar} onClose={() => setDetail(null)}/>} {statement && <StatementModal data={statement} ar={ar} onClose={() => setStatement(null)}/>}
  </Panel>;
}

function AccountDetail({ item, ar, onClose }) {
  const nav = useAppNavigation(); const settlements = item[ar ? 'collections' : 'payments'] || [];
  return <Modal title={`${ar ? '应收' : '应付'}明细 · ${item.source_no}`} onClose={onClose} wide><div className="detail-grid"><div><span>{ar ? '客户' : '供应商'}</span><strong>{item[ar ? 'customerName' : 'supplierName']}</strong></div><div><span>来源</span><strong>{sourceLabels[item.source_type]}</strong></div><div><span>业务日期</span><strong>{item.business_date}</strong></div><div><span>状态</span><Status status={item.status} label={item.statusLabel}/></div><div><span>原始金额</span><strong>{money(item.originalCents)}</strong></div><div><span>冲减</span><strong>{money(item.adjustmentCents)}</strong></div><div><span>{ar ? '已收' : '已付'}</span><strong>{money(item.settledCents)}</strong></div><div><span>{ar ? '未收' : '未付'}</span><strong>{money(item.outstandingCents)}</strong></div></div>
    <div className="relationship-links"><AppLink page={sourcePages[item.source_type]} documentId={item.source_id} documentType={item.source_type}>查看来源单据 {item.source_no}</AppLink></div>
    <h3>核销记录</h3>{settlements.length ? <div className="allocation-list">{settlements.map((row) => <AppLink key={row.id} page={ar ? 'payment-collections' : 'payment-disbursements'} documentId={row.id}><span className="mono">{ar ? row.collectionNo : row.paymentNo}</span><strong>{money(row.allocatedCents)}</strong></AppLink>)}</div> : <Empty text="尚无核销记录"/>}
    <div className="form-actions"><button className="secondary" onClick={onClose}>关闭</button>{nav.canNavigate(ar ? 'payment-collections' : 'payment-disbursements') && item.outstandingCents > 0 && <AppLink className="primary button-link" page={ar ? 'payment-collections' : 'payment-disbursements'}>去{ar ? '收款' : '付款'}</AppLink>}</div></Modal>;
}

function StatementModal({ data, ar, onClose }) { const s = data.summary || {}; return <Modal title={ar ? '客户对账单' : '供应商对账单'} onClose={onClose} wide><div className="settlement-summary"><div><span>查询区间前未结余额</span><strong>{money(s.preRangeOutstandingCents)}</strong></div><div><span>期内{ar ? '应收' : '应付'}增加</span><strong>{money(s.increaseCents)}</strong></div><div><span>{ar ? '销售' : '采购'}退货冲减</span><strong>{money(s.adjustmentCents)}</strong></div><div><span>{ar ? '收款' : '付款'}</span><strong>{money(s.settledCents)}</strong></div><div><span>期末{ar ? '未收' : '未付'}</span><strong>{money(s.endingOutstandingCents)}</strong></div></div><div className="form-actions"><button className="secondary" onClick={onClose}>关闭</button></div></Modal>; }

export function Collections(props) { return <SettlementList {...props} kind="COLLECTION"/>; }
export function Payments(props) { return <SettlementList {...props} kind="PAYMENT"/>; }

function SettlementList({ kind, user, notify }) {
  const { target } = useAppNavigation();
  const collection = kind === 'COLLECTION'; const base = collection ? '/api/payment-collections' : '/api/payment-disbursements'; const responseKey = collection ? 'collections' : 'payments'; const permission = collection ? 'COLLECTION_MANAGE' : 'PAYMENT_MANAGE';
  const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [editor, setEditor] = useState(null); const [detail, setDetail] = useState(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const data = await api(`${base}?search=${encodeURIComponent(search)}&status=${status}`); setItems(data[responseKey] || []); } catch (error) { notify(error.message, 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [status]);
  const open = async (row) => { try { const data = await api(`${base}/${row.id}`); setDetail(data[collection ? 'collection' : 'payment']); } catch (error) { notify(error.message, 'error'); } };
  useEffect(() => { if (target?.page === (collection ? 'payment-collections' : 'payment-disbursements') && target.documentId) void open({ id: target.documentId }); }, [target?.page, target?.documentId]);
  const act = async (action) => { try { await api(`${base}/${detail.id}/${action}`, { method: 'POST', body: {} }); notify(action === 'confirm' ? (collection ? '收款已确认' : '付款已确认') : (collection ? '收款单已取消' : '付款单已取消')); setDetail(null); await load(); } catch (error) { notify(error.message, 'error'); } };
  return <Panel title={collection ? '收款单' : '付款单'} subtitle={`草稿不影响余额；确认后原子核销${collection ? '应收' : '应付'}并生成结算凭证`} action={can(user, permission) && <button className="primary" onClick={() => setEditor({})}>＋ 新增{collection ? '收款' : '付款'}</button>}>
    <Toolbar search={search} setSearch={setSearch} onSearch={load} placeholder={`搜索单号或${collection ? '客户' : '供应商'}`} extra={<select aria-label="单据状态" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="CONFIRMED">已确认</option><option value="CANCELLED">已取消</option></select>}/>
    {loading ? <Loading/> : <div className="table-wrap settlement-table"><table><thead><tr><th>单号</th><th>{collection ? '客户' : '供应商'}</th><th>日期</th><th>方式</th><th className="number">金额</th><th>状态</th></tr></thead><tbody>{items.map((row) => <tr key={row.id} className="clickable" onClick={() => open(row)}><td className="mono strong-text">{row[collection ? 'collectionNo' : 'paymentNo']}</td><td>{row[collection ? 'customerName' : 'supplierName']}</td><td>{row.businessDate}</td><td>{row.paymentMethod === 'CASH' ? '现金' : '银行'}</td><td className="number"><strong>{money(row.amountCents)}</strong></td><td><Status status={row.status} label={row.statusLabel}/></td></tr>)}</tbody></table>{!items.length && <Empty text={`当前没有${collection ? '收款' : '付款'}单`}/>}</div>}
    {editor && <SettlementEditor collection={collection} notify={notify} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); void load(); }}/>} {detail && <DocumentDetail document={detail} collection={collection} canManage={can(user, permission)} onClose={() => setDetail(null)} onAction={act}/>}
  </Panel>;
}

function SettlementEditor({ collection, notify, onClose, onSaved }) {
  const base = collection ? '/api/payment-collections' : '/api/payment-disbursements'; const partyKey = collection ? 'customerId' : 'supplierId'; const sourceKey = collection ? 'receivableId' : 'payableId';
  const [parties, setParties] = useState([]); const [sources, setSources] = useState([]); const [form, setForm] = useState({ [partyKey]: '', businessDate: new Date().toISOString().slice(0, 10), paymentMethod: 'BANK', bankAccount: '', remark: '', allocations: [] });
  useEffect(() => { api(`/api/settlement/${collection ? 'customers' : 'suppliers'}`).then((d) => setParties(d[collection ? 'customers' : 'suppliers'] || [])).catch((e) => notify(e.message, 'error')); }, []);
  useEffect(() => { if (!form[partyKey]) return setSources([]); api(`${collection ? '/api/accounts-receivable?customer=' : '/api/accounts-payable?supplier='}${form[partyKey]}`).then((d) => setSources((d[collection ? 'receivables' : 'payables'] || []).filter((x) => x.outstandingCents > 0))).catch((e) => notify(e.message, 'error')); }, [form[partyKey]]);
  const amountCents = useMemo(() => form.allocations.reduce((sum, row) => sum + (Number(row.amountCents) || 0), 0), [form.allocations]);
  const toggle = (source, checked) => setForm((current) => ({ ...current, allocations: checked ? [...current.allocations, { [sourceKey]: source.id, amountCents: source.outstandingCents }] : current.allocations.filter((row) => row[sourceKey] !== source.id) }));
  const changeAmount = (id, amountCents) => setForm((current) => ({ ...current, allocations: current.allocations.map((row) => row[sourceKey] === id ? { ...row, amountCents } : row) }));
  const save = async (event) => { event.preventDefault(); try { await api(base, { method: 'POST', body: { ...form, amountCents } }); notify('草稿已保存，余额尚未变化'); onSaved(); } catch (error) { notify(error.message, 'error'); } };
  return <Modal title={`新增${collection ? '收款' : '付款'}单`} onClose={onClose} wide><form className="form-grid" onSubmit={save}><label>{collection ? '客户' : '供应商'}<select required value={form[partyKey]} onChange={(e) => setForm({ ...form, [partyKey]: e.target.value, allocations: [] })}><option value="">请选择</option>{parties.map((p) => <option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>业务日期<input type="date" required value={form.businessDate} onChange={(e) => setForm({ ...form, businessDate: e.target.value })}/></label><label>收付方式<select value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}><option value="BANK">银行</option><option value="CASH">现金</option></select></label><label>银行账户备注<input value={form.bankAccount} onChange={(e) => setForm({ ...form, bankAccount: e.target.value })}/></label><label className="full">备注<input value={form.remark} onChange={(e) => setForm({ ...form, remark: e.target.value })}/></label><div className="full"><h3>核销明细</h3><div className="allocation-editor">{sources.map((source) => { const selected = form.allocations.find((row) => row[sourceKey] === source.id); return <div key={source.id} className="allocation-row"><label><input type="checkbox" checked={Boolean(selected)} onChange={(e) => toggle(source, e.target.checked)}/><span><strong>{source.source_no}</strong><small>{source.business_date} · 当前未结 {money(source.outstandingCents)}</small></span></label>{selected && <YuanField ariaLabel={`${source.source_no}核销金额（元）`} valueCents={selected.amountCents} min={0.01} onChangeCents={(value) => changeAmount(source.id, value)} required/>}</div>; })}{form[partyKey] && !sources.length && <Empty text="没有可核销的未结记录"/>}</div><div className="allocation-total"><span>核销合计</span><strong>{money(amountCents)}</strong></div></div><FormActions onClose={onClose} saveText="保存草稿"/></form></Modal>;
}

function DocumentDetail({ document, collection, canManage, onClose, onAction }) { return <Modal title={`${collection ? '收款' : '付款'}单 · ${document[collection ? 'collectionNo' : 'paymentNo']}`} onClose={onClose} wide><div className="detail-grid"><div><span>{collection ? '客户' : '供应商'}</span><strong>{document[collection ? 'customerName' : 'supplierName']}</strong></div><div><span>日期</span><strong>{document.businessDate}</strong></div><div><span>金额</span><strong>{money(document.amountCents)}</strong></div><div><span>状态</span><Status status={document.status} label={document.statusLabel}/></div></div><h3>核销明细</h3><div className="allocation-list">{document.allocations.map((row) => <div key={row[collection ? 'receivableId' : 'payableId']}><span className="mono">{row.sourceNo}</span><strong>{money(row.amountCents)}</strong></div>)}</div><div className="form-actions"><button className="secondary" onClick={onClose}>关闭</button>{canManage && document.status === 'DRAFT' && <><button className="danger-button" onClick={() => onAction('cancel')}>取消草稿</button><button className="primary" onClick={() => onAction('confirm')}>确认并核销</button></>}</div></Modal>; }
