import { Icon } from './icons.jsx';
import { statusLabel } from '../lib/status.js';

export function PageHeader({ title, subtitle, action, large = false }) { return <header className={`page-header${large ? ' page-header--large' : ''}`}><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action && <div className="page-header__action">{action}</div>}</header>; }
export function SectionHeader({ title, subtitle, action }) { return <header className="section-header"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</header>; }
export function GroupedList({ title, children, className = '' }) { return <section className={`grouped-section ${className}`}>{title && <h2>{title}</h2>}<div className="grouped-list">{children}</div></section>; }
export function ListRow({ title, subtitle, meta, status, onClick, children }) { const Tag = onClick ? 'button' : 'div'; return <Tag type={onClick ? 'button' : undefined} className="list-row" onClick={onClick}><div className="list-row__content"><strong>{title}</strong>{subtitle && <span>{subtitle}</span>}{children}</div><div className="list-row__aside">{status}{meta && <small>{meta}</small>}{onClick && <Icon name="chevron" size={18}/>}</div></Tag>; }
export function FormSection({ title, description, children }) { return <fieldset className="form-section"><legend>{title}</legend>{description && <p>{description}</p>}<div className="form-section__body">{children}</div></fieldset>; }
export function FormRow({ label, hint, error, required, children }) { return <label className={`form-row${error ? ' form-row--error' : ''}`}><span className="field-label">{label}{required && <i aria-hidden="true">*</i>}</span>{children}{error ? <small role="alert">{error}</small> : hint && <small>{hint}</small>}</label>; }
export function TextField(props) { return <input {...props}/>; }
export function TextArea(props) { return <textarea {...props}/>; }
export function SelectField({ children, ...props }) { return <select {...props}>{children}</select>; }
export function DateField(props) { return <input type="date" {...props}/>; }
export function MoneyField(props) { return <input type="number" inputMode="decimal" step="0.01" {...props}/>; }
export function QuantityField(props) { return <input type="number" inputMode="decimal" {...props}/>; }
export function PrimaryButton({ className = '', ...props }) { return <button className={`primary ${className}`} {...props}/>; }
export function SecondaryButton({ className = '', ...props }) { return <button className={`secondary ${className}`} {...props}/>; }
export function TertiaryButton({ className = '', ...props }) { return <button className={`ghost ${className}`} {...props}/>; }
export function DestructiveButton({ className = '', ...props }) { return <button className={`danger-button ${className}`} {...props}/>; }
export function IconButton({ label, icon, className = '', ...props }) { return <button type="button" className={`icon-button ${className}`} aria-label={label} {...props}>{icon}</button>; }
export function SegmentedControl({ options, value, onChange, label = '视图选项' }) { return <div className="segmented-control" role="group" aria-label={label}>{options.map((option) => <button type="button" key={option.value} className={value === option.value ? 'is-selected' : ''} aria-pressed={value === option.value} onClick={() => onChange(option.value)}>{option.label}</button>)}</div>; }
export function BottomActionBar({ children }) { return <div className="bottom-action-bar">{children}</div>; }
export function SummaryCard({ label, value, detail }) { return <article className="summary-card"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }

export function SearchField({ value, onChange, onSubmit, placeholder = '搜索', label = placeholder }) { return <form className="search-field" role="search" onSubmit={(event) => { event.preventDefault(); onSubmit?.(); }}><Icon name="search" size={18}/><input aria-label={label} value={value} onChange={(event) => onChange?.(event.target.value)} placeholder={placeholder}/>{value && <button type="button" aria-label="清除搜索" onClick={() => onChange?.('')}><Icon name="close" size={16}/></button>}</form>; }
export function FilterButton({ activeCount = 0, children = '筛选', ...props }) { return <button type="button" className={`filter-button${activeCount ? ' is-active' : ''}`} {...props}><Icon name="filter" size={17}/><span>{children}</span>{activeCount > 0 && <b>{activeCount}</b>}</button>; }
export function Sheet({ title, onClose, children, className = '' }) { return <div className="sheet-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose?.()}><section className={`sheet ${className}`} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" aria-label="关闭" onClick={onClose}><Icon name="close" size={20}/></button></header><div className="sheet__body">{children}</div></section></div>; }
export function FilterSheet({ title = '筛选', onClose, onReset, onApply, children }) { return <Sheet title={title} onClose={onClose} className="filter-sheet"><div className="filter-sheet__fields">{children}</div><BottomActionBar><SecondaryButton type="button" onClick={onReset}>重置</SecondaryButton><PrimaryButton type="button" onClick={onApply}>应用筛选</PrimaryButton></BottomActionBar></Sheet>; }
export function StatusChip({ status, domain, children }) { return <span className={`status-chip status-chip--${String(status || 'unknown').toLowerCase()}`}>{children || statusLabel(status, domain)}</span>; }
export function RecordList({ children, className = '', ...props }) { return <div {...props} className={`record-list ${className}`}>{children}</div>; }
export function RecordCard({ title, subtitle, status, facts = [], actions, onClick, children, className = '', ...props }) { const Tag = onClick ? 'button' : 'article'; return <Tag {...props} type={onClick ? 'button' : undefined} className={`record-card ${className}`} onClick={onClick}><header><div><strong>{title}</strong>{subtitle && <span>{subtitle}</span>}</div>{status}</header>{facts.length > 0 && <dl>{facts.slice(0, 6).map((fact) => <div key={fact.label}><dt>{fact.label}</dt><dd>{fact.value}</dd></div>)}</dl>}{children}{actions && <footer onClick={(event) => event.stopPropagation()}>{actions}</footer>}</Tag>; }
export function DetailSection({ title, action, children }) { return <section className="detail-section"><header><h2>{title}</h2>{action}</header><div className="detail-section__body">{children}</div></section>; }
export function KeyValueRow({ label, value, children }) { return <div className="key-value-row"><span>{label}</span><strong>{children ?? value ?? '—'}</strong></div>; }
export function ActionMenu({ label = '更多操作', children }) { return <details className="canonical-action-menu"><summary aria-label={label}><Icon name="more" size={20}/></summary><div>{children}</div></details>; }
export function ActionSheet({ title = '操作', onClose, children }) { return <Sheet title={title} onClose={onClose} className="action-sheet"><div className="action-sheet__actions">{children}</div></Sheet>; }
export function ConfirmSheet({ title = '确认操作', message, confirmLabel = '确认', onClose, onConfirm, children }) { return <Sheet title={title} onClose={onClose} className="confirm-sheet"><div className="confirm-sheet__message">{children || <p>{message}</p>}</div><BottomActionBar><SecondaryButton type="button" onClick={onClose}>取消</SecondaryButton><PrimaryButton type="button" onClick={onConfirm}>{confirmLabel}</PrimaryButton></BottomActionBar></Sheet>; }
export function DangerSheet({ title = '请确认', message, confirmLabel = '确认', onClose, onConfirm, children }) { return <Sheet title={title} onClose={onClose} className="danger-sheet"><InlineAlert tone="danger">{children || message}</InlineAlert><BottomActionBar><SecondaryButton type="button" onClick={onClose}>取消</SecondaryButton><DestructiveButton type="button" onClick={onConfirm}>{confirmLabel}</DestructiveButton></BottomActionBar></Sheet>; }
export function InlineAlert({ tone = 'info', title, children }) { return <div className={`inline-alert inline-alert--${tone}`} role={tone === 'danger' ? 'alert' : 'status'}>{title && <strong>{title}</strong>}<div>{children}</div></div>; }
export function EmptyState({ title = '暂无数据', description, action }) { return <div className="canonical-empty-state"><Icon name="inbox" size={28}/><strong>{title}</strong>{description && <p>{description}</p>}{action}</div>; }
export function Skeleton({ lines = 3 }) { return <div className="skeleton" role="status" aria-label="加载中">{Array.from({ length: lines }, (_, index) => <span key={index}/>)}</div>; }
export function RelationshipCard({ label, documentNo, status, onClick }) { return <button type="button" className="relationship-card" onClick={onClick}><div><span>{label}</span><strong>{documentNo}</strong></div>{status}{onClick && <Icon name="chevron" size={18}/>}</button>; }
export function LifecycleBadge({ archived, classification }) { const text = archived ? '已归档' : ({ SAFE_DELETE: '可直接删除', SAFE_CHAIN_DELETE: '可整链删除', SAFE_REVERSAL_CLEANUP: '可回滚后清理', ARCHIVE_ONLY: '只能归档', BLOCKED: '当前无法删除' }[classification] || '生命周期待分析'); return <span className={`lifecycle-badge lifecycle-badge--${archived ? 'archived' : String(classification || 'unknown').toLowerCase()}`}>{text}</span>; }
export function DependencyGraphSheet({ graph, onClose, actions }) { return <Sheet title="业务链分析" onClose={onClose} className="dependency-graph-sheet"><div className="dependency-graph-list">{graph?.nodes?.map((node) => <article key={node.key} className={node.selectedForCleanup ? 'is-selected' : 'is-dependent'}><header><strong>{node.documentNo}</strong><StatusChip status={node.status}/></header><span>{node.label}</span><small>{node.effective ? '已有业务影响' : '无库存或财务影响'}{node.period ? ` · ${node.period}` : ''}</small></article>)}</div>{graph?.blockers?.map((blocker) => <InlineAlert key={blocker.code} tone="danger">{blocker.message}</InlineAlert>)}{actions && <BottomActionBar>{actions}</BottomActionBar>}</Sheet>; }
