import {
  Archive, ArrowLeftRight, BadgePercent, Banknote, Bell, Boxes, CalendarClock,
  CalendarDays, ChartNoAxesCombined, Check, CheckCircle2, ChevronLeft,
  ChevronRight, CircleDollarSign, CircleUserRound, ClipboardCheck, ClipboardList,
  Clock3, ContactRound, DatabaseZap, Factory, FileInput, FileText,
  FolderKanban, Grid3X3, Info, Inbox, Landmark, LayoutDashboard, ListChecks,
  MessageCircle, MessageCircleMore, MoreHorizontal, Network, Package,
  PackageCheck, PackageOpen, ReceiptText, RotateCcw, Search, ShieldCheck,
  ShoppingBag, ShoppingCart, SlidersHorizontal, Sparkles, Trash2, TrendingUp,
  TriangleAlert, UserRound, UsersRound, WalletCards, Warehouse, X,
} from 'lucide-react';

const ICONS = {
  message: MessageCircle,
  approval: ClipboardCheck,
  apps: Grid3X3,
  cloud: Sparkles,
  user: CircleUserRound,
  back: ChevronLeft,
  search: Search,
  close: X,
  more: MoreHorizontal,
  filter: SlidersHorizontal,
  inbox: Inbox,
  empty: PackageOpen,
  error: TriangleAlert,
  check: Check,
  info: Info,
  chevron: ChevronRight,
  overview: LayoutDashboard,
  dashboard: Grid3X3,
  orders: ShoppingBag,
  approvals: CheckCircle2,
  purchaseOrders: ShoppingCart,
  suppliers: UsersRound,
  customers: UserRound,
  products: Package,
  warehouses: Warehouse,
  inventory: Boxes,
  purchaseReceipts: FileInput,
  salesDeliveries: PackageCheck,
  returns: RotateCcw,
  inventoryTransactions: ArrowLeftRight,
  reports: ChartNoAxesCombined,
  accountsReceivable: CircleDollarSign,
  accountsPayable: WalletCards,
  paymentCollections: Banknote,
  paymentDisbursements: Banknote,
  accounting: Landmark,
  cashJournals: ReceiptText,
  bankAccounts: Landmark,
  bills: FileText,
  fixedAssets: Archive,
  costAccounting: CircleDollarSign,
  iqc: ShieldCheck,
  oqc: ShieldCheck,
  contacts: ContactRound,
  followups: MessageCircleMore,
  activities: CalendarDays,
  projects: FolderKanban,
  tasks: ListChecks,
  timesheets: Clock3,
  notifications: Bell,
  boms: Network,
  routings: Network,
  forecasts: TrendingUp,
  mrpRuns: CalendarClock,
  materialPlan: ClipboardList,
  mrp: CalendarClock,
  planningDocuments: ClipboardList,
  productionOrders: Factory,
  inventoryScrap: Trash2,
  inventoryPeriod: CalendarClock,
  salesDiscount: BadgePercent,
  purchaseDiscount: BadgePercent,
  users: UsersRound,
  cleanup: DatabaseZap,
};

export function Icon({ name, size = 20, strokeWidth = 1.8, className = '', ...props }) {
  const Component = ICONS[name] || Grid3X3;
  return <Component aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} {...props}/>;
}

export const SearchIcon = (props) => <Icon name="search" {...props}/>;
export const CloseIcon = (props) => <Icon name="close" {...props}/>;
export const MoreIcon = (props) => <Icon name="more" {...props}/>;
export const EmptyIcon = (props) => <Icon name="empty" {...props}/>;
export const ErrorIcon = (props) => <Icon name="error" {...props}/>;
